import type { Technician } from '../../domain/technician.js';

export const syntheticTechnicians: Technician[] = [
  {
    id: 'tech-desert-mobile',
    businessName: 'Desert Mobile RV',
    baseLocation: { city: 'Phoenix', region: 'AZ' },
    serviceRadiusMiles: 45,
    specialties: ['hvac', 'electrical'],
    verified: true,
    availableToday: true,
    responseRate: 0.96,
    rating: 4.9,
    syntheticDistanceMiles: 12,
  },
  {
    id: 'tech-phoenix-rv',
    businessName: 'Phoenix RV Tech',
    baseLocation: { city: 'Mesa', region: 'AZ' },
    serviceRadiusMiles: 35,
    specialties: ['hvac', 'appliance', 'plumbing'],
    verified: true,
    availableToday: true,
    responseRate: 0.88,
    rating: 4.8,
    syntheticDistanceMiles: 18,
  },
  {
    id: 'tech-roof-rescue',
    businessName: 'Sonoran Roof Rescue',
    baseLocation: { city: 'Scottsdale', region: 'AZ' },
    serviceRadiusMiles: 30,
    specialties: ['roof', 'general'],
    verified: true,
    availableToday: false,
    responseRate: 0.92,
    rating: 4.7,
    syntheticDistanceMiles: 15,
  },
  {
    id: 'tech-unverified',
    businessName: 'Quick RV Help',
    baseLocation: { city: 'Phoenix', region: 'AZ' },
    serviceRadiusMiles: 60,
    specialties: ['hvac', 'general'],
    verified: false,
    availableToday: true,
    responseRate: 0.7,
    rating: 4.1,
    syntheticDistanceMiles: 5,
  },
];
